title:  Managed Documentation
description: Managed Documentation
email: lee.gunn@secretorange.co.uk
 
 
 
 
 
color_scheme: "dark"
search_enabled: false
 
author: me

back_to_top: true
back_to_top_text: "Back to top"
 
footer_content: "Copyright &copy; 2021 Me."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

remote_theme: just-the-docs/just-the-docs
